services:
  prod-database:
    image: mysql:latest
    env_file:
      - .env
    container_name: prod-database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - buki-network
  api:
    image: w6d6g6/buki-clone
    container_name: prod-api
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - prod-database
    restart: on-failure
    networks:
      - buki-network

volumes:
  database:
    driver: local

networks:
  buki-network:
    driver: bridge