services:
  prod-database:
    image: mysql:latest
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - prod-database:/var/lib/mysql
  api:
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    network_mode: service:prod-database
    depends_on:
      - prod-database

volumes:
  prod-database:
    driver: local

#Server=localhost;Database=buki;Uid=root;Pwd=secret;
