services:
  database:
    image: mysql:latest
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - buki-dev
    env_file:
      - .env
    volumes:
      - buki-database:/var/lib/mysql
  api-dev-container:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../:/usr/local/buki-app/server
    command: sleep infinity
    user: root
    networks:
      - buki-dev
    ports:
      - "5127:5127"
    depends_on:
      - database

volumes:
  buki-database:
    driver: local

networks:
  buki-dev: